### ISSUE TITLE
Two different success responses: Android and iOS

### ISSUE THREAD

**Issue by iamromec** [razorpay/razorpay-capacitor#10]
This is sick!

On successful payment, it returns two different responses on different platforms.

On Android: `{"response":"{\"razorpay_payment_id\":\"pay_xxxxxxxx\"}"}`

On iOS: `{"response":"pay_xxxxxxxxx"}`

**Comment by iamromec** [comment]
@Nautiyalsachin @vivekshindhe please look into!

**Comment by iamromec** [comment]
If someone else is struggling with this, you can temporarily fix it this way 

```
try {
    const data = (await Checkout.open(options));

    let response: any = {};
    try { 
      response = JSON.parse(data.response); 
    } catch (e) { 
      response = data.response; 
    }
    const paymentId = response.razorpay_payment_id || response;
    successCallback(paymentId);

  } catch (error) {
    errorCallback(error.message);
  }
```

**Comment by Nautiyalsachin** [comment]
@iamromec We are updating these changes in our capacitor plugin, will inform you here as soon as it updates.

**Comment by ketankatdare** [comment]
Have made these response related changes in PR #5. Have a look!

**Comment by atishabhang** [comment]
Much needed. 
Android returns data in property `response` which is serialised, and ios returns only `payment_id`.

**Comment by deepak-csols** [comment]
Is it resolved?

**Comment by iamromec** [comment]
Not yet. You can temporarily follow this to fix if you do not need signature_id.

> If someone else is struggling with this, you can temporarily fix it this way
> 
> ```
> try {
>     const data = (await Checkout.open(options));
> 
>     let response: any = {};
>     try { 
>       response = JSON.parse(data.response); 
>     } catch (e) { 
>       response = data.response; 
>     }
>     const paymentId = response.razorpay_payment_id || response;
>     successCallback(paymentId);
> 
>   } catch (error) {
>     errorCallback(error.message);
>   }
> ```

**Comment by deepak-csols** [comment]
But how can we achieve the signature verification and all. The above code snippet is not secure. When you guys planning to launch a proper merge for it?

**Comment by Nishil20** [comment]
Is it resolved?
Our production build is stuck due to this silly issue.
How I'm able to verify user's payments without razorpay_signature.

**Comment by atishabhang** [comment]
> Is it resolved?
> Our production build is stuck due to this silly issue.
> How I'm going to verify user's payments without razorpay_signature.
> 
> This is the issue of **macOS**
> On macOS Razorpay returns only payment id `{"response":"pay_xxxxxxxxx"}` on both android & ios.

PR pending (https://github.com/razorpay/razorpay-capacitor/pull/5)
till then fork it

**Comment by deadmantfa** [comment]
> Have made these response related changes in PR #5. Have a look!

Why isnt this PR getting pulled. It seems to be working fine just tested it out

**Comment by vivekshindhe** [comment]
This has been resolved. Closing the ticket. Thank you.
