### ISSUE TITLE
Checkout.open return type is not {response: string} it is {response: object}

### ISSUE THREAD

**Issue by gyanidude** [razorpay/razorpay-capacitor#12]
To get the object I had to first JSON.stringify first then JSON.parse like below:

let razorPayTransactionAction = await Checkout.open(options);
JSON.parse(JSON.stringify(razorPayTransactionAction.response));

JSON.parse(razorPayTransactionAction.response) throws error "SyntaxError: Unexpected token o in JSON at position 1"

**Comment by vivekshindhe** [comment]
@gyanidude 

> let data = (await Checkout.open(options)); this.presentAlert(data['response']);

Could you please try it like this? The response in itself is a JSONObject and not a string, hence it didn't work that way.

**Comment by gyanidude** [comment]
I am using with ionic with react, there is no this.presentAlert available in my function.

**Comment by vivekshindhe** [comment]
That is a custom function we create to show alerts.
