### ISSUE TITLE
RazorPay checkout pay overlapping with iphone 12 status bar

### ISSUE THREAD

**Issue by gyanidude** [razorpay/razorpay-capacitor#13]
RazorPay checkout page is overlapping with status bar in iphone 12, because of which it is looking truncated as well as cross icon to close it is also not reachable.
![WhatsApp Image 2021-04-24 at 4 58 09 PM](https://user-images.githubusercontent.com/24972799/115957497-770fe900-a520-11eb-9791-7cb30e1f33a2.jpeg)

**Comment by Nautiyalsachin** [comment]
Hi @gyanidude, Have you installed Cocoapod on your computer, if yes then can you share the razorpay-pod version? You can find Cocoapod version inside **iOS > App > Podfile.lock**.

**Comment by gyanidude** [comment]
Hi team,
I have not installed any razorpay pod.
This is my podfile.lock.

**Comment by Nautiyalsachin** [comment]
I would suggest you check the [Environment Setup](https://capacitorjs.com/docs/v3/getting-started/environment-setup) again, also check all other sections also.

**Comment by gyanidude** [comment]
I have gone through it and I think my setup is write because everything is working fine on iphone 6 and also iphone 12 apart from the UI issue in iphones with notch. Can you please help what should be my next step?

**Comment by Nautiyalsachin** [comment]
@gyanidude Can you share the razorpay-pod version here? you can find the razorpay-pod in ios > podfile.lock

**Comment by gyanidude** [comment]
@Nautiyalsachin 
 - CapacitorRazorpay (0.0.1):
    - Capacitor
    - razorpay-pod (~> 1.1)
  - razorpay-pod (1.1.13)

**Comment by Nautiyalsachin** [comment]
Can you share a sample app here, in the sample app, you can add some test options and our plugin, we want to see your implementation and process.

**Comment by vivekshindhe** [comment]
@gyanidude Closing the ticket due to inactivity. Please feel free to add a comment here to reopen the issue. Or create a new one for the same. Thank you.
