### ISSUE TITLE
Missing com.ionicframework.capacitor.Checkout

### ISSUE THREAD

**Issue by atishabhang** [razorpay/razorpay-capacitor#14]
While adding plugin in android for capacitor. 
Doc mentions about adding `import com.ionicframework.capacitor.Checkout;`.
How can i add this library?

Also Android studio suggest adding `com.razorpay.Checkout`. 
But it doesn't; work 

Earlier I was using razorpay's cordova plugin in capacitor. It worked in android but not in IOS.
Since this library is for capacitor i wanted to update it.

**Comment by tek2991** [comment]
I am having the same issue. Getting error while building the app in Android studio.

error: package com.ionicframework.capacitor does not exist

**Comment by atishabhang** [comment]
Thank you.
I have already solved. It will help others who encounter this issue
