### ISSUE TITLE
unable to install in ionic capacitor project

### ISSUE THREAD

**Issue by amalvarekulam** [razorpay/razorpay-capacitor#16]
try to install  this in a ionic capacitor project 
getting error
npm i -S https://github.com/razorpay/razorpay-capacitor.git
![image](https://user-images.githubusercontent.com/85191642/120373215-b575a080-c335-11eb-873e-5334aa447a6b.png)
 why?
how to solve it. fix asap.

**Comment by vivekshindhe** [comment]
@amalvarekulam We aren't able to reproduce this. But you can try with 
`npm install --save git+https://github.com/razorpay/razorpay-capacitor.git`. This should work in case this still isn't resolved. Closing the ticket for now. Please add a comment here in case you want to reopen the issue, or create another ticket. Thank you.

**Comment by amalvarekulam** [comment]
![image](https://user-images.githubusercontent.com/85191642/122866391-78ee0100-d345-11eb-9dad-ef2f352cceba.png)
Issue still exist

**Comment by vivekshindhe** [comment]
@amalvarekulam You need to make sure you have git installed and properly in your PATH. https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**Comment by vivekshindhe** [comment]
@amalvarekulam Closing the ticket for now. Hoping the issue was resolved. Please add a comment here in case you want to reopen the issue, or create another ticket. Thank you.
