### ISSUE TITLE
Resolve function is not called after first payment fails

### ISSUE THREAD

**Issue by msp-ampcome** [razorpay/razorpay-capacitor#17]
I am using this plugin on Ionic 5 React. 
```
 Checkout.open(options).then((payResponse: any) => {
   console.log(payResponse)
 }).catch((e: any) => {
   console.log(e, 'error')
 })
```
if the payment is successful on the first try, The resolve function passed in the `.then` is called. but if the payment fails and the user retries payment and if it succeeded then resolve function is not getting called. the checkout page closes. I tried to disable the retry option with ```retry```  parameter in options nothing happened. the retry popup still comes up and the user is able to retry the payment. Please provide a way programmatically close the checkout page, so that at least, we can handle the error then close the page.

**Comment by vivekshindhe** [comment]
@msp-ampcome Could you please share the payload you're sending to the library? The options object here?

**Comment by vivekshindhe** [comment]
@msp-ampcome Closing the issue due to inactivity. Please comment here to reopen it. Thank you.
