### ISSUE TITLE
Issues with Android Implementation on Capacitor 3

### ISSUE THREAD

**Issue by vinz-mehra** [razorpay/razorpay-capacitor#18]
I have managed the install the plugin on my app and I can use it fine on the web but while trying to build for android. I am getting errors.

Cannot resolve symbol 'ionicframework'
Cannot resolve symbol 'Checkout'

<img width="697" alt="Screenshot 2021-06-11 at 12 55 12 AM" src="https://user-images.githubusercontent.com/69601568/121585181-e8afe200-ca4f-11eb-8aab-cd09bdcab25e.png">

**Comment by atishabhang** [comment]
If you had Cordova plug-in installed earlier, uninstall both Capacitor and Cordova plug-in and reinstall the capacitor plug-in and then sync.
I faced same issue.

**Comment by vinz-mehra** [comment]
I did fix the issue by deleting the android folder and re-adding it but a new issue surfaced.

Adding the above code is somehow altering the functionality of back button. The app closes on pressing hardware back button instead of going back to previous page.

**Comment by getclear-atish** [comment]
> I did fix the issue by deleting the android folder and re-adding it but a new issue surfaced.
> 
> Adding the above code is somehow altering the functionality of back button. The app closes on pressing hardware back button instead of going back to previous page.

check if angular route history is empty. 
also if check if you upgraded `@angular/router`? 
if its on higher than `10.x.x`, downgrade to `~10`

**Comment by amangoelfv** [comment]
@getclear-atish  why don't it support router versions > 10 .

**Comment by vivekshindhe** [comment]
@amangoelfv @atishGC @vinz-mehra This is still is Continuous Development. We'll roll out versions supporting newer versions in the near future. That being said, closing this ticket. Please add a comment here to reopen or create another ticket in case of an issue. Thank you.

**Comment by kkantaria** [comment]
> I did fix the issue by deleting the android folder and re-adding it but a new issue surfaced.
> 
> Adding the above code is somehow altering the functionality of back button. The app closes on pressing hardware back button instead of going back to previous page.

I still facing same issue
