### ISSUE TITLE
Upstream dependency conflict in Capacitor 3

### ISSUE THREAD

**Issue by WordkeeLearning** [razorpay/razorpay-capacitor#19]
Installing the capacitor is giving the error attached below: 

![cmd_razorpay_error](https://user-images.githubusercontent.com/81528091/122964544-01e85500-d3a5-11eb-8bb1-e4b50852fa74.PNG)

My package.json has capacitor/core 3.0: 

![packagejson_razorpay_error](https://user-images.githubusercontent.com/81528091/122964669-1fb5ba00-d3a5-11eb-9d3b-2547e9fd83e9.PNG)

What resolution can be done?

Please provide a way this plugin can be installed in the project.

**Comment by WordkeeLearning** [comment]
Please advise what to be done in this? As it is critical on the latest version of capacitor.

**Comment by atishabhang** [comment]
Until razorpay updates their plugin for 3.0, maybe you can fork and update the plugin.

**Comment by amanngoel** [comment]
Any updates from the official team ?

**Comment by amanngoel** [comment]
@WordkeeLearning did you find any solution yet ?

**Comment by ggarg2** [comment]
I am also looking for the capacitor 3 solution. In this case, may be we cannot do much. Most probably we have to wait for razopay team.

**Comment by vinz-mehra** [comment]
You can make it work on capacitor 3 project.. follow the below steps.

Install the plugin using this command 

npm i -S https://github.com/razorpay/razorpay-capacitor.git --force 

It will bypass the dependency conflict

Next you need to **remove line 1 to 5** in the definition file of the plugin. razorpay-capacitor/dist/esm/definitions.d.ts 

```
declare module '@capacitor/core' {
    interface PluginRegistry {
        Checkout: CheckoutPlugin;
    }
}
```

This will make it work.

**Comment by krunvaghela** [comment]
I Fixed This issue Here -> https://github.com/krunvaghela/razorpay-capacitor & also created PR https://github.com/razorpay/razorpay-capacitor/pull/22 

Have Great Day

**Comment by tanujlight** [comment]
Any updates from the official team on razorpay-capacitor plugin update for capacitor 3 ?

**Comment by AshokNaik009** [comment]
Not working in Capacitor 2.4.6 ` error: ./node_modules/capacitor-razorpay/dist/esm/web.js 91:17-31`  getting the following issue while running the project  capacitor-razorpay 0.0.1.

**Comment by AshokNaik009** [comment]
> I Fixed This issue Here -> https://github.com/krunvaghela/razorpay-capacitor & also created PR #22
> 
> Have Great Day

Was able to resolve the build issue but after entering card details the Razorpay popup is stuck at payment is being processed loader

**Comment by WordkeeLearning** [comment]
Closing this issue as the Upstream dependency has been fixed by the Razorpay team.

**Comment by AshokNaik009** [comment]
![image](https://user-images.githubusercontent.com/29699443/131211413-7434b227-68f1-45f6-9b4b-87a84cebbd00.png)

Facing this issue while pod installation current ios development target is 12.0

**Comment by vivekshindhe** [comment]
Capacitor needs target version to be 13.0 and above

**Comment by AshokNaik009** [comment]
> Capacitor needs target version to be 13.0 and above

What should be the development target if  using this forked version https://github.com/WordkeeLearning/razorpay-capacitor

**Comment by vivekshindhe** [comment]
Still 13.0

**Comment by AshokNaik009** [comment]
> Still 13.0

@vivekshindhe  No it is not working
![image](https://user-images.githubusercontent.com/29699443/131211939-37ca7418-d44d-4634-ad81-42f30dc03dc3.png)

**Comment by vivekshindhe** [comment]
The error just says that you haven't updated the target version sir.

**Comment by AshokNaik009** [comment]
> The error just says that you haven't updated the target version sir.

Please confirm the at top of the image there it mentioned  IPHONEOS_DEPLOYMENT_TARGET = 13.0; it is from the file project.pbxproj please confirm or please suggest how can I change my target version
