### ISSUE TITLE
Error: package androidx.activity.result does not exist

### ISSUE THREAD

**Issue by gitesh-patil** [razorpay/razorpay-capacitor#24]
I am getting following errors while building for android on iOS its working fine.

Project/node_modules/capacitor-razorpay/android/src/main/java/com/ionicframework/capacitor/Checkout.java:7: error: package androidx.activity.result does not exist
import androidx.activity.result.ActivityResult;
                               ^

Project/node_modules/capacitor-razorpay/android/src/main/java/com/ionicframework/capacitor/Checkout.java:14: error: package com.getcapacitor.annotation does not exist
import com.getcapacitor.annotation.ActivityCallback;

Project/node_modules/capacitor-razorpay/android/src/main/java/com/ionicframework/capacitor/Checkout.java:46: error: cannot find symbol
    private void handleOnActivityResult(PluginCall call, ActivityResult result){
                                                         ^
  symbol:   class ActivityResult
  location: class Checkout

Project/node_modules/capacitor-razorpay/android/src/main/java/com/ionicframework/capacitor/Checkout.java:45: error: cannot find symbol
    @ActivityCallback
     ^
  symbol:   class ActivityCallback
  location: class Checkout

Project/node_modules/capacitor-razorpay/android/src/main/java/com/ionicframework/capacitor/Checkout.java:32: error: cannot find symbol
        call.setKeepAlive(true);
            ^
  symbol:   method setKeepAlive(boolean)
  location: variable call of type PluginCall

Project/node_modules/capacitor-razorpay/android/src/main/java/com/ionicframework/capacitor/Checkout.java:38: error: incompatible types: String cannot be converted to int
            startActivityForResult(call,intent,"handleOnActivityResult");

**Comment by krajendernaik** [comment]
This will solve your problem:
1. Update @capacitor/core,@capacitor/cli,@capacitor/android to 3.1.1
2. change const { Checkout } = Plugins; to import { Checkout } from 'capacitor-razorpay';

if you get any package dependency issues while installing capacitor 3.1.1 then use --force while installing
if any other package is dependent on lower versions of capacitor, install that version too. for e.g. npm i @capacitor/core2@npm:@capacitor/core@2.4.8. And where ever the lower capacitor version is used by any variable change @capacitor/core to @capacitor/core2

if you don't want to touch the previous version of your capacitor, u can follow the above steps for razorpay.

**Comment by vivekshindhe** [comment]
Closing the ticket due to inactivity. Please feel free to comment on the ticket to reopen or create another issue. thank you.
