### ISSUE TITLE
Dependency errors in M1 Macs (Apple Silicon)

### ISSUE THREAD

**Issue by achyuthkodalipages** [razorpay/razorpay-capacitor#25]
I'm developing an IOS app using ionic and capacitor. when I tried to pass the following command I'm getting these errors.

`ionic cap build --prod`

[capacitor]   Found 1 Capacitor plugin for ios:
[capacitor]     capacitor-razorpay (0.0.1)
[capacitor] [error] Analyzing dependencies
[capacitor] /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi/library.rb:275: [BUG] Bus Error at 0x0000000100624000
[capacitor] ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
[capacitor] 
[capacitor] -- Crash Report log information --------------------------------------------
[capacitor]    See Crash Report log file under the one of following:
[capacitor]      * ~/Library/Logs/DiagnosticReports
[capacitor]      * /Library/Logs/DiagnosticReports
[capacitor]    for more details.
[capacitor] Don't forget to include the above Crash Report log file in bug reports.
[capacitor] 
[capacitor] -- Control frame information -----------------------------------------------
[capacitor] c:0058 p:---- s:0372 e:000371 CFUNC  :attach
[capacitor] c:0057 p:0258 s:0366 e:000365 METHOD /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi/library.rb:275
[capacitor] c:0056 p:0050 s:0346 e:000345 CLASS  /Library/Ruby/Gems/2.6.0/gems/ethon-0.14.0/lib/ethon/libc.rb:17
[capacitor] c:0055 p:0007 s:0343 e:000342 CLASS  /Library/Ruby/Gems/2.6.0/gems/ethon-0.14.0/lib/ethon/libc.rb:7
[capacitor] c:0054 p:0007 s:0340 e:000339 TOP    /Library/Ruby/Gems/2.6.0/gems/ethon-0.14.0/lib/ethon/libc.rb:2 [FINISH]
[capacitor] c:0053 p:---- s:0337 e:000336 CFUNC  :require
[capacitor] c:0052 p:0110 s:0332 e:000331 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54
[capacitor] c:0051 p:0042 s:0320 e:000319 TOP    /Library/Ruby/Gems/2.6.0/gems/ethon-0.14.0/lib/ethon.rb:15 [FINISH]
[capacitor] c:0050 p:---- s:0317 e:000316 CFUNC  :require
[capacitor] c:0049 p:0110 s:0312 e:000311 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54
[capacitor] c:0048 p:0013 s:0300 e:000299 TOP    /Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2 [FINISH]
[capacitor] c:0047 p:---- s:0297 e:000296 CFUNC  :require
[capacitor] c:0046 p:0110 s:0292 e:000291 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54
[capacitor] c:0045 p:0006 s:0280 e:000279 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.2/lib/cocoapods-core/cdn_source.rb:440
[capacitor] c:0044 p:0045 s:0272 e:000271 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.2/lib/cocoapods-core/cdn_source.rb:372
[capacitor] c:0043 p:0318 s:0261 e:000260 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.2/lib/cocoapods-core/cdn_source.rb:365
[capacitor] c:0042 p:0006 s:0251 e:000250 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.2/lib/cocoapods-core/cdn_source.rb:338
[capacitor] c:0041 p:0040 s:0246 e:000245 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.2/lib/cocoapods-core/cdn_source.rb:284
[capacitor] c:0040 p:0073 s:0239 e:000238 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.2/lib/cocoapods-core/cdn_source.rb:208
[capacitor] c:0039 p:0008 s:0230 e:000229 BLOCK  /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.2/lib/cocoapods-core/source/aggregate.rb:83 [FINISH]
[capacitor] c:0038 p:---- s:0226 e:000225 CFUNC  :select
[capacitor] c:0037 p:0008 s:0222 e:000221 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.2/lib/cocoapods-core/source/aggregate.rb:83
[capacitor] c:0036 p:0011 s:0216 e:000215 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/resolver.rb:416
[capacitor] c:0035 p:0101 s:0211 e:000207 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/resolver.rb:385
[capacitor] c:0034 p:0051 s:0200 e:000199 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/resolver.rb:360
[capacitor] c:0033 p:0059 s:0192 e:000189 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/resolver.rb:165
[capacitor] c:0032 p:0066 s:0183 e:000178 BLOCK  /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/resolver.rb:274 [FINISH]
[capacitor] c:0031 p:---- s:0174 e:000173 IFUNC 
[capacitor] c:0030 p:---- s:0171 e:000170 CFUNC  :each
[capacitor] c:0029 p:---- s:0168 e:000167 CFUNC  :sort_by
[capacitor] c:0028 p:0006 s:0164 e:000163 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/resolver.rb:267
[capacitor] c:0027 p:0014 s:0157 e:000156 BLOCK  /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53
[capacitor] c:0026 p:0002 s:0154 e:000153 METHOD /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70
[capacitor] c:0025 p:0005 s:0148 e:000147 METHOD /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52
[capacitor] c:0024 p:0029 s:0141 e:000140 METHOD /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754
[capacitor] c:0023 p:0051 s:0131 e:000130 METHOD /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746
[capacitor] c:0022 p:0047 s:0125 e:000124 METHOD /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729
[capacitor] c:0021 p:0114 s:0121 e:000120 METHOD /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686
[capacitor] c:0020 p:0010 s:0115 e:000114 METHOD /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254
[capacitor] c:0019 p:0082 s:0110 e:000109 METHOD /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182
[capacitor] c:0018 p:0037 s:0106 e:000105 METHOD /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43
[capacitor] c:0017 p:0049 s:0100 e:000099 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/resolver.rb:94
[capacitor] c:0016 p:0041 s:0094 e:000093 BLOCK  /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:1074
[capacitor] c:0015 p:0081 s:0090 e:000089 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64
[capacitor] c:0014 p:0078 s:0083 e:000082 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:1072
[capacitor] c:0013 p:0161 s:0076 e:000075 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:124
[capacitor] c:0012 p:0011 s:0061 e:000060 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:414
[capacitor] c:0011 p:0007 s:0056 e:000055 BLOCK  /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:239
[capacitor] c:0010 p:0081 s:0053 e:000052 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64
[capacitor] c:0009 p:0048 s:0046 e:000045 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:238
[capacitor] c:0008 p:0009 s:0040 e:000039 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:160
[capacitor] c:0007 p:0054 s:0036 e:000035 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command/install.rb:52
[capacitor] c:0006 p:0078 s:0031 e:000030 METHOD /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334
[capacitor] c:0005 p:0024 s:0024 e:000023 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command.rb:52
[capacitor] c:0004 p:0378 s:0019 e:000018 TOP    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/bin/pod:55 [FINISH]
[capacitor] c:0003 p:---- s:0013 e:000012 CFUNC  :load
[capacitor] c:0002 p:0109 s:0008 E:001240 EVAL   /usr/local/bin/pod:23 [FINISH]
[capacitor] c:0001 p:0000 s:0003 E:0026e0 (none) [FINISH]
[capacitor] 
[capacitor] -- Ruby level backtrace information ----------------------------------------
[capacitor] /usr/local/bin/pod:23:in `<main>'
[capacitor] /usr/local/bin/pod:23:in `load'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/bin/pod:55:in `<top (required)>'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command.rb:52:in `run'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command/install.rb:52:in `run'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:160:in `install!'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64:in `section'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:414:in `analyze'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64:in `section'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor sync ios exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.

NOTE: I've seen the official documentation and added the following code snippet in Podfile, even after adding this snippet i'm not able to build the project.

`platform :ios, '11.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorRazorpay', :path => '../../node_modules/capacitor-razorpay'
end

target 'App' do
  capacitor_pods
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end`

**Comment by vivekshindhe** [comment]
@achyuthkodalipages We believe using rosetta should solve this error for you. Closing the ticket.
