### ISSUE TITLE
Issue in Capacitor 2.4.6

### ISSUE THREAD

**Issue by AshokNaik009** [razorpay/razorpay-capacitor#27]
![image](https://user-images.githubusercontent.com/29699443/130594958-2103c31a-7dba-48d6-b064-9ad86f4f4432.png)

**Comment by vivekshindhe** [comment]
@AshokNaik009 you can do 
` npm install https://github.com/razorpay/razorpay-capacitor.git#596df6b7088b31b9f272b9d904fc90bea8815702 `
For using capacitor 2.X

**Comment by vivekshindhe** [comment]
Closing the ticket due to inactivity. Please feel free to comment here to reopen or create another issue. Thank you
