### ISSUE TITLE
error on : @capacitor/core@3.1.2

### ISSUE THREAD

**Issue by anilcop** [razorpay/razorpay-capacitor#28]
code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: xyze@0.0.1
npm ERR! Found: @capacitor/core@3.1.2
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"3.1.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^2.4.6" from capacitor-razorpay@0.0.1
npm ERR! node_modules/capacitor-razorpay
npm ERR!   capacitor-razorpay@"https://github.com/razorpay/razorpay-capacitor.git" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by vivekshindhe** [comment]
@anilcop This has been updated. We have updated our Capacitor plugin to version 3.X.X. This should be resolved now. Closing the ticket. Thank you.
