### ISSUE TITLE
Activity com.razorpay.CheckoutActivity has leaked IntentReceiver

### ISSUE THREAD

**Issue by iamromec** [razorpay/razorpay-capacitor#31]
Hello,

I've looked for all possible solutions to this issue but nothing helped.

We're using the latest capacitor version (3.1.1) and the latest version of this plugin, but still, this issue persists. It happens when a user goes back to the app by 'CLICKING ON APP ICON' instead of opening the app from 'TRAY or RECENT APPS' after making payment or switching between a UPI app.

It closes the Razorpay checkout window and throws a below-attached error.

<img width="1385" alt="Screenshot 2021-10-04 at 8 11 15 PM" src="https://user-images.githubusercontent.com/50284628/135872542-aa02592d-4f23-4093-a135-5685d1869e63.png">

I tried reaching the integration team but none helped. They shared this link: https://stackoverflow.com/questions/18449541/android-application-restarts-when-opened-by-clicking-the-application-icon/21407931 which is not similar to this issue.

Please help.

**Comment by iamromec** [comment]
Due to this particular issue and UPI Intent where UPI apps are not redirecting a user to the app is causing is many payment failures.

I've attached screenshot of where payments are stuck in Authorised status due to this:

<img width="366" alt="Screenshot 2021-10-06 at 7 33 47 PM" src="https://user-images.githubusercontent.com/50284628/136218719-97626cd9-e244-471c-9b9e-f07ee89cb9d4.png">
  

@Nautiyalsachin @vivekshindhe would you guys please help us?

**Comment by vivekshindhe** [comment]
@iamromec I'm guessing we were able to resolve this issue with you on the ticket itself. Updating here for anyone else, in AndroidManifest.xml, the line launchMode="single" should be removed to ensure that the activity is kept in the background. Regarding the issue in the first post here, we have resolved it. It is in version 1.6.15. We will be updating it in capacitor plugin. Or you can do it manually as well. Closing the ticket. Thank you.
