### ISSUE TITLE
Payments are not being captured due to no Order Id

### ISSUE THREAD

**Issue by iamromec** [razorpay/razorpay-capacitor#32]
Hello Team,

We have recently detected that payments from some payment methods are not being captured via the API (Node.js). When we reached your support team they mentioned that it's because the transaction does not have an order id.

I'm sure there should be a way where Order Id can be generated through this plugin integration itself instead of manually using the Order API to create one (which is not applicable in the case of Capacitor Plugin Integration).

Please fix it asap as orders are not being processed due to this issue. We have to manually capture the payment most of the time.

Mostly we've seen this through PhonePay and due to this reason, we had to disable the PhonePay payment method temporarily.

Let me know if you need any information.

**Comment by vivekshindhe** [comment]
The reason for order generation not available in any of our SDK or plugins is security purposes. We will look into this. No ETA as of yet. Closing the issue for now.
