### ISSUE TITLE
Playstore Update Rejected - Your app contains an intent redirection vulnerability

### ISSUE THREAD

**Issue by skadimoolam** [razorpay/razorpay-capacitor#61]
Hi there,

Today an update to our Capacitor app was rejected by the play store.

Please check these images
![image](https://user-images.githubusercontent.com/6323063/215278790-fd6e4673-c66a-413c-af94-048c8d064a13.png)

![image](https://user-images.githubusercontent.com/6323063/215278805-6bc860dd-ecce-4374-b92c-8974e87f4894.png)

We use the latest 1.2.0 version of capacitor-razorpay package with Vite 4

This seems to be an issue downstream in the razorpay's android SDK, or I might be wrong.

What could cause this issue and how to fix it?

Thank You.

**Comment by abuhurairalakdawala** [comment]
I am facing the same issue since today.
@skadimoolam were you able to solve this ?

**Comment by skadimoolam** [comment]
@abuhurairalakdawala I've not been able to solve this issue, but for us we have to ship this update, so I took another build of the same app and uploaded to google, it showed the same error on Google play Admin but also published the update.

I tried to downgrade the Razorpay Checkout version manually but it did not help.

**Comment by ratnamyadav** [comment]
I am also facing same issue for the new app i am deploying to play store.

**Comment by abuhurairalakdawala** [comment]
Ok, this has to be fixed from this package. Need someone from contributor of this repo to help.
Can someone tag those who can help ?

**Comment by skadimoolam** [comment]
@vivekshindhe @Nautiyalsachin

**Comment by vivekshindhe** [comment]
Hey folks, we noticed this issue and have fixed it. Please reinstall the package and upload to playstore.

**Comment by skadimoolam** [comment]
Hi @vivekshindhe 

Yes, I can confirm that it's no longer an issue, I just pushed an update to one of my apps and it did show the same error.

@abuhurairalakdawala @ratnamyadav

**Comment by vivekshindhe** [comment]
Hey, @skadimoolam just to clarify. You are not facing this issue anymore right?

**Comment by skadimoolam** [comment]
Yes, this issue is no more. After updating the com.razorpay:Checkout package
