### ISSUE TITLE
Capacitor 6 support 

### ISSUE THREAD

**Issue by Aksoom-Hussain** [razorpay/razorpay-capacitor#85]
when we can expect the v6
is there any plan for the same

v5 still not mention in docs 
it a workaround for everyone to go through the close issue 
[here](https://github.com/razorpay/razorpay-capacitor/issues/73#issuecomment-1965894937
)
or at least add it in description

**Comment by iamromec** [comment]
Why this plugin is not being maintained? Capacitor is on 6 currently but this is still on 3.

<img width="1019" alt="Screenshot 2024-04-20 at 7 25 33 PM" src="https://github.com/razorpay/razorpay-capacitor/assets/50284628/be25d80d-e779-4ebd-b151-ed35177c5f52">

**Comment by iamromec** [comment]
@vivekshindhe

**Comment by iamromec** [comment]
When will this be sorted out? We're getting notifications from Google Play. 

<img width="1380" alt="Screenshot 2024-04-22 at 12 19 15 PM" src="https://github.com/razorpay/razorpay-capacitor/assets/50284628/c39bdce2-b99d-481d-86ce-bfb0113d284e">

**Comment by iamromec** [comment]
@vivekshindhe another issue we're seeing is here:
![Uploading Simulator Screenshot - iPhone 15 - 2024-04-23 at 16.39.58.png…]()

**Comment by iamromec** [comment]
@shashankkumar any update? @pronav

**Comment by vivekshindhe** [comment]
@iamromec , the pop-up only happens in the debug flow. On prod flows, this isn't visible. Also, support for capacitor v6 has been released. 

> When will this be sorted out? We're getting notifications from Google Play.
> 
> <img alt="Screenshot 2024-04-22 at 12 19 15 PM" width="1380" src="https://private-user-images.githubusercontent.com/50284628/324357999-c39bdce2-b99d-481d-86ce-bfb0113d284e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTk4MjcsIm5iZiI6MTcxOTI5OTUyNywicGF0aCI6Ii81MDI4NDYyOC8zMjQzNTc5OTktYzM5YmRjZTItYjk5ZC00ODFkLTg2Y2UtYmZiMDExM2QyODRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA3MTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ODI1NTg1NWI5Y2VmYzdkOThlNDRmMmZkNjI0MTA1ODNmNWQ4ZjU4ZTc1MDZmZmU1Njc1YTc2ODhkOWVhZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oNINk35QFBGdmjGRKYF20YzsSY0z1IXCGPXf1-5tsp4">

This has been fixed a while ago. Would request you to sync the grade files by opening the android project of your capacitor application so the latest SDKs can be downloaded.

Closing this ticket. Please reply on this ticket or open another ticket in case of issues.
