### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by himanshusukhpal** [razorpay/razorpay-capacitor#9]
> npm i -S https://github.com/razorpay/razorpay-capacitor.git
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/razorpay/razorpay-capacitor.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Himanshu Sukhpal\AppData\Local\npm-cache\_logs\2021-04-06T07_24_35_603Z-debug.log

Can't install the plugin getting this error, need to add  Razorpay payment option to my app

**Comment by Nautiyalsachin** [comment]
@himanshusukhpal Can you try again, we have done some changes around this, which can help you in installing.

**Comment by himanshusukhpal** [comment]
@Nautiyalsachin no, still getting the same error
reify timing arborist:ctor Completed in 0ms
idealTree: timing arborist:ctor Completed in 0ms
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/razorpay/razorpay-capacitor.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

Currently, I am manually downloading the repository and adding it to the node modules, that way the payment gateway is working on both iOS and Android both, but the capacitor-razorpay directory gets removed every time NPM is run

**Comment by Nautiyalsachin** [comment]
@himanshusukhpal, try creating a sample app first, also I would recommend you to update the capacitor and npm in your laptop to the latest. Let me know if you are still stuck.

**Comment by himanshusukhpal** [comment]
@Nautiyalsachin 
Ionic:

   Ionic CLI                     : 6.13.0 (C:\Users\Himanshu Sukhpal\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1101.1
   @angular-devkit/schematics    : 11.1.1
   @angular/cli                  : 11.1.1
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.5

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   NodeJS : v15.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 7.6.0
   OS     : Windows 10

Tried it in a new project as well -
PS D:\ShiftKarado\ShiftKaradoCodeBase\newproj> npm i -S https://github.com/razorpay/razorpay-capacitor.git
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/razorpay/razorpay-capacitor.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Himanshu Sukhpal\AppData\Local\npm-cache\_logs\2021-04-22T09_26_08_044Z-debug.log

I believe the problem is your project isn't available on npm, the npm link given on your project is broken

**Comment by Nautiyalsachin** [comment]
@himanshusukhpal We are working on a new update which will fix this issue, please give us some time here. Thank you.

**Comment by himanshusukhpal** [comment]
Okay
